abort install on error

diff --git a/installmodules b/installmodules
--- a/installmodules
+++ b/installmodules
@@ -5,21 +5,29 @@
 # 20170905 Paul Huygen
 # 20180507 Paul Huygen
 thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd )"
+res=0
+
+function update_res () {
+    tres=$1
+    if
+	[ $tres -gt 0 ]
+    then
+	res=tres
+    fi
+    
+}
+
+function handle_failure () {
+    errmess=$1
+    if
+	[ $res -gt 0 ]
+    then
+	echo $errmess > &2
+	exit 4
+    fi
+
 source $thisdir/source
-#if
-#    [ ! -z ${1+x} ]
-#then
-#    source $1
-#else
-#    source /usr/local/bin/source
-#fi
-# set -e
-# modulesocket=/usr/local/nlpp
-# modulesdir=${modulesocket}/nlppmodules
 mkdir -p $modulesdir
-#secretrepodir=newsreader@kyoto.let.vu.nl:v4.0.0.0_nlpp_resources
-#secretkey=${pipesocket}/nrkey
-#echo key: ${secretkey} >&2
 
 # Occasionally cloning from git fails, but the failure is not reproducible. Therefore, repeat cloning if it fails.
 
@@ -33,8 +41,8 @@ function install_from_git () {
     local reponame=$1
     local repourl=$2
     local commitset=$3
-    local maxtrials=10
-    local res=0
+    local maxtrialses=10
+    local tres=0
     local trial=0
     local go_on=0
     cd ${modulesdir}
@@ -42,16 +50,18 @@ function install_from_git () {
 	[ $go_on == 0 ]
     do
  	git clone $repourl
-	res=$?
+	tres=$?
 	if
-	    [ $res == 0 ]
+	    [ $tres == 0 ]
 	then
 	    cd $reponame
 	    git checkout $commitset
+	    update_res $?
 	    if
 		[ -x "./install" ]
 	    then
 		./install
+	        update_res $?
 	    fi
 	    go_on=1
 	else
@@ -61,9 +71,11 @@ function install_from_git () {
 	    then
 		go_on=1
 		echo "GIT FAIL: cloning of $repourl failed $maxtrials times" >&2
+		exit 4
 	    fi
 	fi
     done
+    handle_failure "Cannot install module $reponame from Github"
     cd ${modulesdir}
 }
 
@@ -72,23 +84,27 @@ function  install_from_repo {
   local modulename=$1
   local ball=$2
   cd ${modulesdir}
+  update_res $?
   if
-      [ -e $repodir/$ball ]
+      [ ! -e $repodir/$ball ]
   then
-      echo "Install $modulename from $ball" >&2
-      tar -xzf ${repodir}/${ball}
-#     rm ${ball}
-      cd ${modulesdir}/${modulename}
-      if
-	  [ -e install ]
-      then
-	  ./install &>./install.log
-      fi
-  else
-#      scp -i ${secretkey} ${secretrepodir}/${ball} .
-      echo "Not installing $modulename from $ball" >&2
+      echo "Cannot $modulename from $ball" >&2
+      exit 4
+  fi
+  echo "Install $modulename from $ball" >&2
+  tar -xzf ${repodir}/${ball}
+  update_res $?
+# rm ${ball}
+  cd ${modulesdir}/${modulename}
+  update_res $?
+  if
+  	  [ -e install ]
+  then
+  	  ./install &>./install.log
+  	  update_res $?
   fi
   cd ${modulesdir}
+  handle_failure "Cannot install $modulename from repo"
 }
 
 #
