wip nlpp script

diff --git a/run/nlpp b/run/nlpp
--- a/run/nlpp
+++ b/run/nlpp
@@ -2,10 +2,16 @@
 # testit -- test newly installed pipeline
 # 20170907 Paul Huygen
 export thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+bindir=${thisdir}
 export confdir=/usr/local/etc/nlpp
+if
+    [ "$1" == 'k' ]
+then
+    keep_temp=0
+fi
 initscript=${confdir}/conf
 source $initscript
-scratchdir=`mkdir -d -t nlpp.XXXXXX`
+scratchdir=`mktemp -d -t nlpp.XXXXXX`
 res=0
 
 function runmodule {
@@ -19,16 +25,16 @@ function runmodule {
 
 # run_pipeline -- run the pipeline
 # Assume current dir is work-dir, contains in.naf.
-function run_pipeline {
+function run_pipeline () {
     naflang=$1
     modulelist=${confdir}/modules.${naflang}
     lastfile=in.naf
     while
 	IFS=' ' read -r module || [[ -n "$module" ]]
     do
-	echo "Annotate ${lastfile} with ${module}"
+	echo "Annotate ${lastfile} with ${module}" >&2
         nextfile=${module}.naf
-        cat ${lastfile} | ${MODROOT}/${module} >${module.naf}
+        cat ${lastfile} | ${MODROOT}/${module}/run >${module}.naf
 	res=$?
 	if
 	    [ ${res} -gt 0 ]
@@ -46,18 +52,25 @@ cd $scratchdir
 cat >in.naf
 export naflang=`cat in.naf | $bindir/langdetect.py`
 if
-    [ "$naflang" != "nl" -o "$naflang" != "en" ]
+    [ "$naflang" != "nl" -a "$naflang" != "en" ]
 then
-    echo "Language $naflang is not supported."
+    echo "Language $naflang is not supported." >&2
     exit 4
 fi
 run_pipeline $naflang
-
-
-export NAFLANG='nl'
-run_pipeline ${thisdir}/testnl ${thisdir}/test.nl.in.naf ${thisdir}/modules.nl
 if
     [ $res -gt 0 ]
 then
-    echo "Pipeline has not been completed due to an error."
+    echo "Pipeline has not been completed due to an error." >&2
+    exit 4
 fi
+cat out.naf
+if
+    [ $keep_temp == 0 ]
+then
+    echo "$scratchdir kept" >&2
+else
+    rm -rf $scratchdir
+fi
+
+
