replace EHU-srl-server by ixa-pipe-srl

diff --git a/run/nlpp b/run/nlpp
--- a/run/nlpp
+++ b/run/nlpp
@@ -2,17 +2,42 @@
 # testit -- test newly installed pipeline
 # 20170907 Paul Huygen
 export thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
+oldd=`pwd`
 bindir=${thisdir}
 export confdir=/usr/local/etc/nlpp
-keep_temp=1
-if
-    [ "$1" == 'k' ]
-then
-    keep_temp=0
-fi
+progname=$0
+unset keep_temp
+unset workdir
+
+function show_help () {
+echo "usage: $progname [-k] [-t workdir ] < infile > outfile"
+echo "infile : raw naf"
+echo "outfile : annotated naf"
+echo "-k : Keep intermediate results in the workdir"
+echo "-t : use workdir for intermediate results"
+}
+
+while getopts "h?vkt:" opt; do
+    case "$opt" in
+    h|\?)
+        show_help
+        exit 0
+        ;;
+    v)  verbose=1
+        ;;
+    k)  keep_temp=0
+        ;;
+    t)  workdir=$OPTARG
+    esac
+done
+
 initscript=${confdir}/conf
 source $initscript
-scratchdir=`mktemp -d -t nlpp.XXXXXX`
+if
+    [ -z ${workdir+x} ]
+then
+    workdir=`mktemp -d -t nlpp.XXXXXX`
+fi
 res=0
 
 function runmodule {
@@ -40,6 +65,7 @@ function run_pipeline () {
 	if
 	    [ ${res} -gt 0 ]
 	then
+	    echo "Module ${module} failed." >&2
 	    break
 	fi
 	lastfile=${module}.naf
@@ -47,9 +73,7 @@ function run_pipeline () {
     ln -s ${lastfile} out.naf
 }
 
-
-
-cd $scratchdir
+cd $workdir
 cat >in.naf
 export naflang=`cat in.naf | $bindir/langdetect.py`
 if
@@ -58,7 +82,9 @@ then
     echo "Language $naflang is not supported." >&2
     exit 4
 fi
+res=0
 run_pipeline $naflang
+cd $oldd
 if
     [ $res -gt 0 ]
 then
@@ -67,11 +93,11 @@ then
 fi
 cat out.naf
 if
-    [ $keep_temp == 0 ]
+    [ -z ${keep_temp+x} ]
 then
-    echo "$scratchdir kept" >&2
+    rm -rf $workdir
 else
-    rm -rf $scratchdir
+    echo "$workdir kept" >&2
 fi
 
 
diff --git a/test/testit b/test/testit
--- a/test/testit
+++ b/test/testit
@@ -1,45 +1,49 @@
 #!/bin/bash
 # testit -- test newly installed pipeline
 # 20170907 Paul Huygen
+export scriptname=$0
 export thisdir="$( cd "$( dirname "${BASH_SOURCE[0]}" )" && pwd)"
-initscript=${thisdir}/conf
-source $initscript
-# export MODROOT=/usr/local/nlpp/nlppmodules
-mkdir -p testen
-mkdir -p testnl
-res=0
+export socket="$(dirname $thisdir)"
+export rundir=${socket}/run
+source $rundir/conf
+unset NAFLANG
 
-function runmodule {
-   local infile=$1
-   local modnam=$2
-   local outfile=$3
-   cat ${infile} | $MODROOT/${modnam}/run > ${outfile}
-   res=$?
+while getopts ":l:" opt; do
+  case $opt in
+    l) NAFLANG=$OPTARG
+      ;;
+    \?)
+      echo "Invalid option: -$OPTARG" >&2
+      exit 1
+      ;;
+    :)
+      echo "Option -$OPTARG requires an argument." >&2
+      exit 1
+      ;;
+  esac
+done
+
+function testrun () {
+    testlang=$1
+    testdir=${thisdir}/test${testlang}
+    mkdir -p ${testdir}
+    rm -rf ${testdir}/*.naf
+#    cp ${thisdir}/test.${testlang}.in.naf ${testdir}/in.naf
+    ${rundir}/nlpp -k -t ${testdir} < ${thisdir}/test.${testlang}.in.naf >/dev/null
 }
 
-
-# run_pipeline -- run the pipeline
-# args:
-# 1: directory to run the pipeline in
-# 2: input naf
-# 3: path to file with list of modules
-function run_pipeline {
-    local rundir=$1
-    local infile=$2
-    local modulelist=$3
-    local lastfile=$infile
-    cd $rundir
-    while
-	IFS=' ' read -r module || [[ -n "$module" ]]
-    do
-	echo "Annotate ${lastfile} with ${module}"
-	runmodule ${lastfile} ${module} ${module}.naf
-	lastfile=${module}.naf
-    done < ${modulelist}
-    ln -s ${lastfile} out.naf
-}
-
-export NAFLANG='en'
-run_pipeline ${thisdir}/testen ${thisdir}/test.en.in.naf ${thisdir}/modules.en
-export NAFLANG='nl'
-run_pipeline ${thisdir}/testnl ${thisdir}/test.nl.in.naf ${thisdir}/modules.nl
+if
+    [ -z ${NAFLANG+x} ]
+then
+    $scriptname -l "en"
+    $scriptname -l "nl"
+else
+    if
+	[ "$NAFLANG" == 'en' -o "$NAFLANG" == 'nl' ]
+    then
+	testrun "$NAFLANG"
+    else
+	echo "Invalid language: $NAFLANG."
+	exit 1
+    fi
+fi
